services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8880:80'
      - '8281:81'
      - '4043:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  
  nginx-hello-world:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '8080:80'